# Generated by Django 2.0.6 on 2024-03-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_autor_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
